name: Clone, Upload, Deploy to Pages, and Callback

on:
  workflow_dispatch:
    inputs:
      websiteUrl:
        description: 'Website URL to clone'
        required: true
        type: string
      email:
        description: 'User Email for notification'
        required: true
        type: string

permissions:
  contents: write

jobs:
  clone_deploy_callback:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.final_status.outputs.status }}
      preview_url: ${{ steps.final_status.outputs.preview_url }}
      error_message: ${{ steps.final_status.outputs.error_message }}
    env: # <-- DEFINE ENV VARS AT JOB LEVEL
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      GH_TOKEN: ${{ secrets.CLOUDFLARE_WORKER_PAT }} # Make PAT available to all steps in the job
    steps:
      - name: Initialize Status
        id: status_init
        run: |
          echo "status=pending" >> $GITHUB_OUTPUT
          echo "error_message=Workflow started" >> $GITHUB_OUTPUT
          echo "preview_url=''" >> $GITHUB_OUTPUT

      - name: Install required tools
        id: install_tools
        run: |
          sudo apt-get update && sudo apt-get install -y httrack jq # Only install httrack and jq via apt
          # git, gh, curl, npm are usually pre-installed on ubuntu-latest
          # Verify pre-installed tools (optional, for confirmation)
          echo "Verifying tools..."
          which git
          which gh
          which curl
          which jq
          which httrack
          which npm
          npm --version
          echo "status=running_install" >> $GITHUB_OUTPUT

      - name: Configure git
        id: configure_git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Migration Bot"
          echo "status=running_git_config" >> $GITHUB_OUTPUT

      - name: Verify GitHub CLI Authentication (Implicit via GH_TOKEN)
        id: authenticate_gh
        # No need for 'env:' block here anymore, it inherits from the job level
        run: |
          echo "Verifying GH CLI authentication using GH_TOKEN env var..."
          gh auth status # This should now work using the job-level GH_TOKEN
          echo "GH CLI authentication appears successful."
          echo "status=running_gh_auth" >> $GITHUB_OUTPUT

      - name: Run httrack to mirror website
        id: httrack_clone
        run: |
          OUTPUT_DIR="cloned_website_${{ github.run_id }}"
          echo "Cloning ${{ github.event.inputs.websiteUrl }} into $OUTPUT_DIR"
          httrack "${{ github.event.inputs.websiteUrl }}" \
            -O "$OUTPUT_DIR" \
            --depth=1 \
            --stay-on-same-address \
            --user-agent "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" \
            --disable-security-limits \
            --robots=0 \
            --verbose \
            +*.png +*.gif +*.jpg +*.jpeg +*.svg +*.css +*.js # Common file types
          # Basic check if httrack created the directory and index file
          if [ ! -d "$OUTPUT_DIR" ] || [ ! -f "$OUTPUT_DIR/index.html" ]; then
            echo "HTTrack failed to create output directory or index.html"
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "error_message=HTTrack failed to clone the site properly." >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "output_dir=$OUTPUT_DIR" >> $GITHUB_OUTPUT
          echo "status=running_httrack" >> $GITHUB_OUTPUT

      - name: Create new GitHub repository
        id: create_repo
        if: steps.authenticate_gh.outcome == 'success' && steps.httrack_clone.outcome == 'success' # Added auth check
        # No need for 'env:' block here anymore (except for step-specific vars like GH_REPO_NAME)
        env:
          GH_REPO_NAME: "migrated-${{ github.run_id }}" # Unique repo name
          GH_REPO_DESCRIPTION: "Migrated site for ${{ github.event.inputs.websiteUrl }}"
        run: |
          echo "Creating repository ${{ github.repository_owner }}/${GH_REPO_NAME}"
          # gh command will implicitly use the job-level GH_TOKEN
          if ! gh repo create "${{ github.repository_owner }}/${GH_REPO_NAME}" --public --description "$GH_REPO_DESCRIPTION" --clone=false; then
             echo "Failed to create GitHub repository."
             echo "status=failure" >> $GITHUB_OUTPUT
             echo "error_message=Failed to create the GitHub repository." >> $GITHUB_OUTPUT
             exit 1
          fi
          echo "repo_name=${GH_REPO_NAME}" >> $GITHUB_OUTPUT
          echo "status=running_repo_create" >> $GITHUB_OUTPUT

      - name: Initialize repository and push mirror
        id: push_code
        if: steps.create_repo.outcome == 'success'
        # No need for explicit GH_TOKEN in 'env:' here
        run: |
          REPO_NAME="${{ steps.create_repo.outputs.repo_name }}"
          OUTPUT_DIR="${{ steps.httrack_clone.outputs.output_dir }}"
          # Use the job-level GH_TOKEN for the repo URL
          REPO_URL="https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${REPO_NAME}.git"

          echo "Pushing code to $REPO_NAME"
          cd "$OUTPUT_DIR" || exit 1
          git init -b main
          git remote add origin "$REPO_URL"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Initial mirror of ${{ github.event.inputs.websiteUrl }}"
            if ! git push -u origin main; then
                sleep 5
                if ! git push -u origin main; then
                    echo "Failed to push code to GitHub repository after retry."
                    echo "status=failure" >> $GITHUB_OUTPUT
                    echo "error_message=Failed to push code to the GitHub repository." >> $GITHUB_OUTPUT
                    exit 1
                fi
            fi
          else
            echo "No changes detected to commit."
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "error_message=HTTrack downloaded an empty site or failed to find content." >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "status=running_push_code" >> $GITHUB_OUTPUT

      - name: Deploy to Cloudflare Pages
        id: deploy_pages
        if: steps.push_code.outcome == 'success' # Make sure push succeeded
        run: |
          REPO_NAME="${{ steps.create_repo.outputs.repo_name }}"
          PROJECT_NAME="${REPO_NAME}" # Use repo name for CF Pages project name
          REPO_URL="https://github.com/${{ github.repository_owner }}/${REPO_NAME}"

          echo "Deploying $REPO_NAME to Cloudflare Pages as $PROJECT_NAME"
          # Run wrangler using npx and capture output (including stderr)
          # PREPEND npx here VVVVV
          DEPLOY_OUTPUT=$(npx wrangler pages deploy "$REPO_URL" --project-name="$PROJECT_NAME" --branch="main" 2>&1)
          echo "$DEPLOY_OUTPUT" # Log output for debugging

          # Check wrangler exit status explicitly
          WRANGLER_EXIT_CODE=$?
          if [ $WRANGLER_EXIT_CODE -ne 0 ]; then
             echo "Wrangler command failed with exit code $WRANGLER_EXIT_CODE."
             echo "$DEPLOY_OUTPUT" # Print error output
             echo "status=failure" >> $GITHUB_OUTPUT
             echo "error_message=Wrangler deployment command failed (Code: $WRANGLER_EXIT_CODE)." >> $GITHUB_OUTPUT
             exit 1
          fi

          # Extract the deployment URL (adjust grep/sed if output format changes)
          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://.*\.pages\.dev')

          if [ -z "$PREVIEW_URL" ]; then
             echo "Failed to deploy to Cloudflare Pages or extract URL from output."
             echo "$DEPLOY_OUTPUT" # Print potentially useful output even if URL isn't found
             echo "status=failure" >> $GITHUB_OUTPUT
             echo "error_message=Failed to deploy or extract Cloudflare Pages URL." >> $GITHUB_OUTPUT
             exit 1
          fi

          echo "Deployment successful: $PREVIEW_URL"
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT # Mark success only after successful deployment
           
           # This step consolidates the final status for the callback
      - name: Set Final Status
        id: final_status
        # Always runs, uses outputs from previous steps or failure flags
        if: always() # Ensure this step runs even if previous ones fail/are skipped
        run: |
          # Default to failure unless deploy_pages explicitly succeeded
          FINAL_STATUS="failure"
          FINAL_PREVIEW_URL=""
          FINAL_ERROR_MSG="An unexpected error occurred or a previous step failed/was skipped."

          # Check the outcome of the deploy step first
          if [ "${{ steps.deploy_pages.outcome }}" == "success" ] && [ ! -z "${{ steps.deploy_pages.outputs.preview_url }}" ]; then
            FINAL_STATUS="success"
            FINAL_PREVIEW_URL="${{ steps.deploy_pages.outputs.preview_url }}"
            FINAL_ERROR_MSG=""
          # If deploy didn't succeed, provide a more specific error based on what failed
          elif [ "${{ steps.httrack_clone.outcome }}" != "success" ]; then
            FINAL_ERROR_MSG="HTTrack failed to clone the site. Outcome: ${{ steps.httrack_clone.outcome }}"
          elif [ "${{ steps.create_repo.outcome }}" != "success" ]; then
            FINAL_ERROR_MSG="Failed to create GitHub repository. Outcome: ${{ steps.create_repo.outcome }}"
          elif [ "${{ steps.push_code.outcome }}" != "success" ]; then
            FINAL_ERROR_MSG="Failed to push code to GitHub. Outcome: ${{ steps.push_code.outcome }}"
          elif [ "${{ steps.deploy_pages.outcome }}" != "success" ]; then
            FINAL_ERROR_MSG="Failed to deploy to Cloudflare Pages. Outcome: ${{ steps.deploy_pages.outcome }}"
          fi

          echo "status=${FINAL_STATUS}" >> $GITHUB_OUTPUT
          echo "preview_url=${FINAL_PREVIEW_URL}" >> $GITHUB_OUTPUT
          echo "error_message=${FINAL_ERROR_MSG}" >> $GITHUB_OUTPUT

      - name: Send Callback to Cloudflare Worker
        # Always run this step to report status
        if: always()
        env:
          CALLBACK_URL: ${{ secrets.CLOUDFLARE_WORKER_CALLBACK_URL }}
          USER_EMAIL: ${{ github.event.inputs.email }}
          WEBSITE_URL: ${{ github.event.inputs.websiteUrl }}
          # Use the outputs from the robust final_status step
          STATUS: ${{ steps.final_status.outputs.status }}
          PREVIEW_URL: ${{ steps.final_status.outputs.preview_url }}
          ERROR_MSG: ${{ steps.final_status.outputs.error_message }}
        run: |
          echo "Sending callback to $CALLBACK_URL"
          echo "Status: $STATUS"
          echo "Preview URL: $PREVIEW_URL"
          echo "Error: $ERROR_MSG"

          # Ensure STATUS is never empty before sending
          if [ -z "$STATUS" ]; then
            echo "::error:: STATUS is empty, setting to failure before callback."
            STATUS="failure"
            ERROR_MSG="Workflow failed to determine final status."
          fi

          # Construct JSON payload using jq for safety
          JSON_PAYLOAD=$(jq -n \
            --arg status "$STATUS" \
            --arg email "$USER_EMAIL" \
            --arg website "$WEBSITE_URL" \
            --arg url "$PREVIEW_URL" \
            --arg error "$ERROR_MSG" \
            '{status: $status, userEmail: $email, websiteUrl: $website, previewUrl: $url, errorMessage: $error}')

          echo "Payload: $JSON_PAYLOAD"

          # Send POST request
          curl -X POST "$CALLBACK_URL" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            --fail --silent --show-error # Make curl fail on HTTP errors and show them
