name: Clone Website and Upload

on:
  workflow_dispatch:
    inputs:
      websiteUrl:
        description: 'Website URL to clone'
        required: true
        type: string
      email:
        description: 'User Email (for notification - optional)'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  deployments: write
  repository-projects: write
  actions: read
  checks: write

jobs:
  clone_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y httrack git gh

      - name: Run httrack to mirror website
        id: httrack_clone
        run: |
          OUTPUT_DIR="cloned_website"
          httrack "${{ github.event.inputs.websiteUrl }}" \
            -O "$OUTPUT_DIR" \
            --depth=10 \
            --mirror \
            --user-agent "Mozilla/5.0" \
            --disable-security-limits \
            --robots=0 \
            +*.js
          echo "output_dir=$OUTPUT_DIR" >> $GITHUB_OUTPUT

      - name: Configure git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.CloudflareWorker }}" | gh auth login --with-token

      - name: Create a new repository
        id: create_repo
        env:
          REPO_NAME: "cloned-website-${{ github.run_id }}"
          REPO_DESCRIPTION: "Cloned website of ${{ github.event.inputs.websiteUrl }}"
        run: |
          gh repo create "${{ github.repository_owner }}/${REPO_NAME}" \
            --public \
            --description "$REPO_DESCRIPTION" \
            --clone=false
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Initialize repository and push mirror
        run: |
          REPO_NAME="${{ steps.create_repo.outputs.repo_name }}"
          OUTPUT_DIR="${{ steps.httrack_clone.outputs.output_dir }}"
          REPO_URL="https://${{ github.repository_owner }}:${{ secrets.CloudflareWorker }}@github.com/${{ github.repository_owner }}/${REPO_NAME}.git"

          cd "$OUTPUT_DIR"
          git init
          git remote add origin "$REPO_URL"
          git add .
          git commit -m "Mirrored website from ${{ github.event.inputs.websiteUrl }}"
          git push -u origin main
