name: Mirror Website and Push to New Repo

on:
  repository_dispatch:
    types: [trigger-httrack]

permissions:
  contents: write
  issues: write
  repository-projects: write
  actions: write
  pull-requests: write
  id-token: write

jobs:
  trigger-httrack:
    runs-on: ubuntu-latest
    steps:
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y httrack git gh

      - name: Run httrack to mirror website
        run: |
          httrack "${{ github.event.client_payload.website }}" \
            --depth=10 \
            --mirror \
            --user-agent "Mozilla/5.0" \
            --disable-security-limits \
            --robots=0 \
            +*.js

      - name: Configure git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create a new repository
        env:
          GH_TOKEN: ${{ secrets.GITHUBTOKEN_TOKEN }}  # Set GH_TOKEN here
          NEW_REPO_NAME: ${{ github.event.client_payload.repo_name }}
        run: |
          # Create a new public repository; add --private if you prefer private.
          gh repo create "${{ github.repository_owner }}/${NEW_REPO_NAME}" --public --confirm

      - name: Initialize repository and push mirror
        env:
          GH_TOKEN: ${{ secrets.GITHUBTOKEN_TOKEN }}
          NEW_REPO_NAME: ${{ github.event.client_payload.repo_name }}
        run: |
          git init
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Set the remote URL with the token embedded
          git remote add origin https://github.com/${{ github.repository_owner }}/${NEW_REPO_NAME}.git
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository_owner }}/${NEW_REPO_NAME}.git"
          git add .
          git commit -m "Mirrored website from ${{ github.event.client_payload.website }}"
          git push -u origin master
